package cn.itcast.mybatis.domain;

import java.math.BigDecimal;

public class ContractProductC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private String contractProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.CONTRACT_ID
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.FACTORY_ID
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private String factoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.PRODUCT_NAME
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.PRODUCT_NO
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private String productNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.PRODUCT_IMAGE
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private String productImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.PRODUCT_DESC
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.CNUMBER
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private BigDecimal cnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.OUT_NUMBER
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private BigDecimal outNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.LOADING_RATE
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private String loadingRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.BOX_NUM
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private BigDecimal boxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.PACKING_UNIT
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private String packingUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.PRICE
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.AMOUNT
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.FINISHED
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private BigDecimal finished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.EXTS
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private String exts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_C.ORDER_NO
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    private BigDecimal orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @return the value of CONTRACT_PRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public String getContractProductId() {
        return contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @param contractProductId the value for CONTRACT_PRODUCT_C.CONTRACT_PRODUCT_ID
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setContractProductId(String contractProductId) {
        this.contractProductId = contractProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.CONTRACT_ID
     *
     * @return the value of CONTRACT_PRODUCT_C.CONTRACT_ID
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.CONTRACT_ID
     *
     * @param contractId the value for CONTRACT_PRODUCT_C.CONTRACT_ID
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.FACTORY_ID
     *
     * @return the value of CONTRACT_PRODUCT_C.FACTORY_ID
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public String getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.FACTORY_ID
     *
     * @param factoryId the value for CONTRACT_PRODUCT_C.FACTORY_ID
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setFactoryId(String factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.PRODUCT_NAME
     *
     * @return the value of CONTRACT_PRODUCT_C.PRODUCT_NAME
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.PRODUCT_NAME
     *
     * @param productName the value for CONTRACT_PRODUCT_C.PRODUCT_NAME
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.PRODUCT_NO
     *
     * @return the value of CONTRACT_PRODUCT_C.PRODUCT_NO
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.PRODUCT_NO
     *
     * @param productNo the value for CONTRACT_PRODUCT_C.PRODUCT_NO
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.PRODUCT_IMAGE
     *
     * @return the value of CONTRACT_PRODUCT_C.PRODUCT_IMAGE
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.PRODUCT_IMAGE
     *
     * @param productImage the value for CONTRACT_PRODUCT_C.PRODUCT_IMAGE
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.PRODUCT_DESC
     *
     * @return the value of CONTRACT_PRODUCT_C.PRODUCT_DESC
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.PRODUCT_DESC
     *
     * @param productDesc the value for CONTRACT_PRODUCT_C.PRODUCT_DESC
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.CNUMBER
     *
     * @return the value of CONTRACT_PRODUCT_C.CNUMBER
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public BigDecimal getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.CNUMBER
     *
     * @param cnumber the value for CONTRACT_PRODUCT_C.CNUMBER
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setCnumber(BigDecimal cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.OUT_NUMBER
     *
     * @return the value of CONTRACT_PRODUCT_C.OUT_NUMBER
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public BigDecimal getOutNumber() {
        return outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.OUT_NUMBER
     *
     * @param outNumber the value for CONTRACT_PRODUCT_C.OUT_NUMBER
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setOutNumber(BigDecimal outNumber) {
        this.outNumber = outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.LOADING_RATE
     *
     * @return the value of CONTRACT_PRODUCT_C.LOADING_RATE
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public String getLoadingRate() {
        return loadingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.LOADING_RATE
     *
     * @param loadingRate the value for CONTRACT_PRODUCT_C.LOADING_RATE
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setLoadingRate(String loadingRate) {
        this.loadingRate = loadingRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.BOX_NUM
     *
     * @return the value of CONTRACT_PRODUCT_C.BOX_NUM
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public BigDecimal getBoxNum() {
        return boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.BOX_NUM
     *
     * @param boxNum the value for CONTRACT_PRODUCT_C.BOX_NUM
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setBoxNum(BigDecimal boxNum) {
        this.boxNum = boxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.PACKING_UNIT
     *
     * @return the value of CONTRACT_PRODUCT_C.PACKING_UNIT
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public String getPackingUnit() {
        return packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.PACKING_UNIT
     *
     * @param packingUnit the value for CONTRACT_PRODUCT_C.PACKING_UNIT
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setPackingUnit(String packingUnit) {
        this.packingUnit = packingUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.PRICE
     *
     * @return the value of CONTRACT_PRODUCT_C.PRICE
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.PRICE
     *
     * @param price the value for CONTRACT_PRODUCT_C.PRICE
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.AMOUNT
     *
     * @return the value of CONTRACT_PRODUCT_C.AMOUNT
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.AMOUNT
     *
     * @param amount the value for CONTRACT_PRODUCT_C.AMOUNT
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.FINISHED
     *
     * @return the value of CONTRACT_PRODUCT_C.FINISHED
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public BigDecimal getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.FINISHED
     *
     * @param finished the value for CONTRACT_PRODUCT_C.FINISHED
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setFinished(BigDecimal finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.EXTS
     *
     * @return the value of CONTRACT_PRODUCT_C.EXTS
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public String getExts() {
        return exts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.EXTS
     *
     * @param exts the value for CONTRACT_PRODUCT_C.EXTS
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setExts(String exts) {
        this.exts = exts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_C.ORDER_NO
     *
     * @return the value of CONTRACT_PRODUCT_C.ORDER_NO
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public BigDecimal getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_C.ORDER_NO
     *
     * @param orderNo the value for CONTRACT_PRODUCT_C.ORDER_NO
     *
     * @mbggenerated Sun Nov 08 00:23:50 CST 2015
     */
    public void setOrderNo(BigDecimal orderNo) {
        this.orderNo = orderNo;
    }
}